222 wires
AnthonyTornetta/Cosmos pull request #276
Opened 2024-07-06 19:04 UTC by DanielStebbins

Completed:
- Logic graph with wires, logic on block, and logic indicator light.
- Logic groups that merge and split as wires connect them.
- Logic events for outputs and inputs (in that order) in each frame.

To do (issues created):
- Logic gates.
- Colored logic wires.
- Logic interactions with existing blocks, for example, missile launchers.

2024-07-06 19:46 UTC, AnthonyTornetta requested changes

2024-07-06 19:46 UTC, AnthonyTornetta commented on cosmos_client/assets/cosmos/blocks/logic_indicator.json
> +        "Sides": {
Can be "Single": "cosmos:light" I think

2024-07-06 19:46 UTC, AnthonyTornetta commented on cosmos_core/src/block/specific_blocks/logic_indicator.rs
> +        (self.0 >> 7) & 1 == 0
Put this "7" into a constant so it's not a magic number

2024-07-06 19:46 UTC, AnthonyTornetta commented on cosmos_core/src/logic/logic_graph.rs
> +    fn all_for(coords: BlockCoordinate) -> HashSet<Port> {
Use HashSet::from_iter here

2024-07-06 19:46 UTC, AnthonyTornetta commented on cosmos_core/src/logic/logic_graph.rs
> +        if let Ok(neighbor_coords) = coords.step(local_face) {
Swap to `let else` for less indentation in method

2024-07-06 19:46 UTC, AnthonyTornetta commented on cosmos_core/src/logic/logic_graph.rs
> +        if logic_block.wire_faces().count() > 0 {
does this have the .is_empty() method? also early return here would be ideal for less indentation

2024-07-06 19:46 UTC, AnthonyTornetta commented on cosmos_core/src/logic/logic_graph.rs
> +        if logic_block.wire_faces().count() > 0 {
same as above

2024-07-06 19:46 UTC, AnthonyTornetta commented on cosmos_core/src/logic/mod.rs
> +        if let Some(logic_block) = logic_blocks.from_id(blocks.from_numeric_id(ev.old_block).unlocalized_name()) {
let else for less indent.

2024-07-06 19:46 UTC, AnthonyTornetta commented on cosmos_core/src/structure/coordinates.rs
>          #[doc=$structComment]
Please derive default for this too then

2024-07-06 19:48 UTC, AnthonyTornetta commented
Lot of expects in logic_graph.rs, at some point we may want to go back and see if we can rearchitect the graph a bit to remove some of them, and not represent as many invalid states.  But for a first creation of a logical/wire system, this is great.

2024-07-06 21:38 UTC, DanielStebbins commented on cosmos_core/src/logic/mod.rs
> +        if let Some(logic_block) = logic_blocks.from_id(blocks.from_numeric_id(ev.old_block).unlocalized_name()) {
No, I like the indent

2024-07-07 00:54 UTC, AnthonyTornetta requested changes

2024-07-07 00:54 UTC, AnthonyTornetta commented on cosmos_client/src/ui/components/text_input.rs
> +                // focused.0 = None;
Uncomment this

2024-07-07 15:04 UTC, AnthonyTornetta approved these changes

2024-07-07 15:04 UTC, merged